language: python
matrix:
  include:
    - env: TOX_ENV=py27
      python: "2.7"
    - env: TOX_ENV=py34
      python: "3.4"
    - env: TOX_ENV=py35
      python: "3.5"
    - env: TOX_ENV=py36
      python: "3.6"
    - env: TOX_ENV=py37
      python: "3.7"
    - env: TOX_ENV=py38
      python: "3.8"
    - env: TOX_ENV=py39
      python: "3.9"
    - env: TOX_ENV=lint
install: pip install tox
script: tox -e $TOX_ENV
cache: pip
